import type { Diagram, DiagramLegendItem } from '@enitt/diagram';

/** 특정 업무 영역에 종속되지 않은 요청 처리 흐름 예시. */
export const requestFlow: Diagram = {
  nodes: [
    { id: 'start', type: 'start', x: 70, y: 220, label: '요청 접수' },
    {
      id: 'validate',
      type: 'process',
      x: 220,
      y: 220,
      label: '입력 검증',
      sublabel: 'Schema v2',
      status: 'success',
    },
    {
      id: 'decision',
      type: 'decision',
      x: 390,
      y: 220,
      label: '승인 필요?',
      status: 'active',
    },
    {
      id: 'automatic',
      type: 'process',
      x: 570,
      y: 110,
      label: '자동 처리',
      status: 'active',
      annotations: [{ text: '평균 1.2초' }],
    },
    {
      id: 'review',
      type: 'process',
      x: 570,
      y: 330,
      label: '담당자 검토',
      status: 'warning',
      annotations: [{ text: '대기 18분', emphasis: true }],
    },
    {
      id: 'store',
      type: 'database',
      x: 740,
      y: 220,
      label: '결과 저장',
      status: 'success',
    },
    { id: 'end', type: 'end', x: 900, y: 220, label: '완료', status: 'success' },
    {
      id: 'note',
      type: 'note',
      x: 390,
      y: 360,
      label: '승인 기준',
      sublabel: '금액·권한 정책',
      status: 'muted',
      labelPlacement: 'right',
    },
  ],
  links: [
    { id: 'start-validate', from: 'start:right', to: 'validate:left', direction: 'forward' },
    {
      id: 'validate-decision',
      from: 'validate:right',
      to: 'decision:left',
      direction: 'forward',
      status: 'success',
    },
    {
      id: 'decision-auto',
      from: 'decision:top',
      to: 'automatic:left',
      direction: 'forward',
      label: '아니요',
      status: 'active',
    },
    {
      id: 'decision-review',
      from: 'decision:bottom',
      to: 'review:left',
      direction: 'forward',
      label: '예',
      status: 'warning',
    },
    {
      id: 'auto-store',
      from: 'automatic:right',
      to: 'store:top',
      direction: 'forward',
      status: 'active',
    },
    {
      id: 'review-store',
      from: 'review:right',
      to: 'store:bottom',
      direction: 'forward',
      status: 'warning',
    },
    {
      id: 'store-end',
      from: 'store:right',
      to: 'end:left',
      direction: 'forward',
      status: 'success',
    },
    {
      id: 'note-decision',
      from: 'note:top',
      to: 'decision:bottom',
      style: 'dotted',
      status: 'muted',
    },
  ],
};

export const requestFlowLegend: readonly DiagramLegendItem[] = [
  { status: 'active', label: '진행 중' },
  { status: 'success', label: '완료' },
  { status: 'warning', label: '확인 필요' },
  { status: 'muted', label: '참고' },
];
