import type { Diagram } from '@enitt/diagram';

/**
 * 수전설비 단선결선도 예시.
 *
 * 한전 수전 → DS → VCB → 주변압기 → 저압 모선 → 피더 6회선.
 * 좌표는 도면 좌표계이며, 화면 크기와 무관하다.
 */
export const substation: Diagram = {
  nodes: [
    {
      id: 'src',
      type: 'source',
      x: 400,
      y: 40,
      label: '한전 수전',
      sublabel: '22.9 kV',
      state: 'energized',
      measurements: [{ text: '22.8 kV' }],
    },
    {
      id: 'ds-1',
      type: 'disconnector',
      x: 400,
      y: 120,
      label: 'DS-1',
      state: 'energized',
      switchState: 'closed',
    },
    {
      id: 'vcb-1',
      type: 'breaker',
      x: 400,
      y: 200,
      label: 'VCB-1',
      sublabel: '630 A',
      state: 'energized',
      switchState: 'closed',
    },
    {
      id: 'tr-1',
      type: 'transformer',
      x: 400,
      y: 280,
      label: 'TR-1',
      sublabel: '22.9 kV / 380 V, 1000 kVA',
      state: 'fault',
      measurements: [{ text: '118 °C', emphasis: true }],
    },
    {
      id: 'bus-main',
      type: 'bus',
      x: 400,
      y: 360,
      length: 680,
      orientation: 'horizontal',
      label: 'MAIN BUS',
      state: 'energized',
      measurements: [{ text: '381 V · 1.42 MW · PF 0.96' }],
    },

    {
      id: 'acb-1',
      type: 'breaker',
      x: 120,
      y: 430,
      label: 'ACB-1',
      state: 'energized',
      switchState: 'closed',
    },
    {
      id: 'load-1',
      type: 'load',
      x: 120,
      y: 510,
      label: '생산 1동',
      sublabel: '520 kW',
      state: 'energized',
    },

    {
      id: 'acb-2',
      type: 'breaker',
      x: 260,
      y: 430,
      label: 'ACB-2',
      state: 'energized',
      switchState: 'closed',
    },
    {
      id: 'load-2',
      type: 'load',
      x: 260,
      y: 510,
      label: '생산 2동',
      sublabel: '610 kW',
      state: 'energized',
      measurements: [{ text: '95%', emphasis: true }],
    },

    {
      id: 'acb-3',
      type: 'breaker',
      x: 400,
      y: 430,
      label: 'ACB-3',
      state: 'energized',
      switchState: 'closed',
    },
    {
      id: 'load-3',
      type: 'load',
      x: 400,
      y: 510,
      label: '사무동',
      sublabel: '180 kW',
      state: 'energized',
    },

    {
      id: 'acb-4',
      type: 'breaker',
      x: 540,
      y: 430,
      label: 'ACB-4',
      state: 'deenergized',
      switchState: 'open',
    },
    { id: 'load-4', type: 'load', x: 540, y: 510, label: '예비회선', state: 'deenergized' },

    {
      id: 'acb-pv',
      type: 'breaker',
      x: 660,
      y: 430,
      label: 'ACB-PV',
      state: 'energized',
      switchState: 'closed',
    },
    {
      id: 'pv-1',
      type: 'pv',
      x: 660,
      y: 510,
      label: 'PV-1',
      sublabel: '300 kWp',
      state: 'energized',
      measurements: [{ text: '214 kW' }],
    },

    {
      id: 'acb-ess',
      type: 'breaker',
      x: 740,
      y: 430,
      label: 'ACB-ESS',
      state: 'maintenance',
      switchState: 'open',
    },
    {
      id: 'ess-1',
      type: 'ess',
      x: 740,
      y: 510,
      label: 'ESS-1',
      sublabel: 'SOC 42%',
      state: 'maintenance',
    },

    {
      id: 'gnd-tr',
      type: 'ground',
      x: 470,
      y: 320,
      state: 'grounded',
      label: '중성점 접지',
      labelPlacement: 'right',
    },
  ],
  links: [
    { id: 'l-src-ds', from: 'src:bottom', to: 'ds-1:top', state: 'energized', flow: 'forward' },
    { id: 'l-ds-vcb', from: 'ds-1:bottom', to: 'vcb-1:top', state: 'energized', flow: 'forward' },
    { id: 'l-vcb-tr', from: 'vcb-1:bottom', to: 'tr-1:top', state: 'energized', flow: 'forward' },
    { id: 'l-tr-bus', from: 'tr-1:bottom', to: 'bus-main', state: 'energized', flow: 'forward' },
    { id: 'l-tr-gnd', from: 'tr-1:bottom', to: 'gnd-tr:top', state: 'grounded' },

    { id: 'l-bus-acb1', from: 'bus-main', to: 'acb-1:top', state: 'energized' },
    {
      id: 'l-acb1-load1',
      from: 'acb-1:bottom',
      to: 'load-1:top',
      state: 'energized',
      flow: 'forward',
    },
    { id: 'l-bus-acb2', from: 'bus-main', to: 'acb-2:top', state: 'energized' },
    {
      id: 'l-acb2-load2',
      from: 'acb-2:bottom',
      to: 'load-2:top',
      state: 'energized',
      flow: 'forward',
    },
    { id: 'l-bus-acb3', from: 'bus-main', to: 'acb-3:top', state: 'energized' },
    {
      id: 'l-acb3-load3',
      from: 'acb-3:bottom',
      to: 'load-3:top',
      state: 'energized',
      flow: 'forward',
    },
    { id: 'l-bus-acb4', from: 'bus-main', to: 'acb-4:top', state: 'energized' },
    { id: 'l-acb4-load4', from: 'acb-4:bottom', to: 'load-4:top', state: 'deenergized' },
    { id: 'l-bus-acbpv', from: 'bus-main', to: 'acb-pv:top', state: 'energized' },
    {
      id: 'l-acbpv-pv',
      from: 'acb-pv:bottom',
      to: 'pv-1:top',
      state: 'energized',
      flow: 'reverse',
    },
    { id: 'l-bus-acbess', from: 'bus-main', to: 'acb-ess:top', state: 'energized' },
    { id: 'l-acbess-ess', from: 'acb-ess:bottom', to: 'ess-1:top', state: 'maintenance' },
  ],
};
